import { Inter, Itim } from "next/font/google";
import { Caveat } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const caveat = Caveat({
    weight: "400",
    subsets: ["latin"],
    variable: "--font-caveat",
});
const itim = Itim({
    weight: "400",
    subsets: ["latin"],
    variable: "--font-itim",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="scroll-smooth" data-theme="hey">
            <head>
                <link
                    rel="icon"
                    href="/icon?<generated>"
                    type="image/<generated>"
                    sizes="<generated>"
                />
                <link rel="icon" href="/2.ico" sizes="any" />
                <meta name="theme-color" content="#fafafa" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <title>Vishal</title>
            </head>
            <body
                data-atm-ext-installed="true"
                className={`${caveat.variable} ${itim.variable}`}
            >
                {children}
            </body>
        </html>
    );
}
