import { Inter, Itim } from "next/font/google";
import { Caveat } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const caveat = Caveat({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-caveat",
});
const itim = Itim({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-itim",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${caveat.variable} ${itim.variable}`}>{children}</body>
    </html>
  );
}
